In [1]:
import pandas as pd

In [2]:
df_netflix = pd.read_csv('datasets/netflix_titles.csv')

In [3]:
df_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Unnamed: 12
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN

In [4]:
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
 12  Unnamed: 12   1 non-null      object
dtypes: int64(1), object(12)
memory usage: 894.6+ KB

In [5]:

df_netflix_titles = df_netflix.drop(['show_id', 'cast', 'rating', 'duration', 
                'description', 'Unnamed: 12'], axis=1)

In [6]:
df_netflix_titles.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [7]:
df_netflix_titles.date_added = pd.to_datetime(df_netflix_titles.date_added)

In [8]:
df_netflix_titles

,type,title,director,country,date_added,release_year,listed_in
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,Documentaries
1,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,"International TV Shows, TV Dramas, TV Mysteries"
2,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,"Crime TV Shows, International TV Shows, TV Act..."
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,"Docuseries, Reality TV"
4,TV Show,Kota Factory,NaN,India,2021-09-24,2021,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,United States,2019-11-20,2007,"Cult Movies, Dramas, Thrillers"
8803,TV Show,Zombie Dumb,NaN,NaN,2019-07-01,2018,"Kids' TV, Korean TV Shows, TV Comedies"
8804,Movie,Zombieland,Ruben Fleischer,United States,2019-11-01,2009,"Comedies, Horror Movies"
8805,Movie,Zoom,Peter Hewitt,United States,2020-01-11,2006,"Children & Family Movies, Comedies"
8806,Movie,Zubaan,Mozez Singh,India,2019-03-02,2015,"Dramas, International Movies, Music & Musicals"

In [9]:
df_netflix_catalogue = df_netflix_titles.rename(columns={'listed_in': 'category'})

In [10]:
df_netflix_catalogue.head()

,type,title,director,country,date_added,release_year,category
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,Documentaries
1,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,"International TV Shows, TV Dramas, TV Mysteries"
2,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,"Crime TV Shows, International TV Shows, TV Act..."
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,"Docuseries, Reality TV"
4,TV Show,Kota Factory,NaN,India,2021-09-24,2021,"International TV Shows, Romantic TV Shows, TV ..."

<table><tr><td class="selected" colspan="1" rowspan="1" style="display: table-cell; text-align: left;"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>Data classification</span></p></div></div></td></tr><tr><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>type</span></p></div></div></td><td colspan="1" rowspan="1" style="display: table-cell; text-align: left;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>categórico nominal, str</span></p></div></div></td></tr><tr><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>title</span></p></div></div></td><td colspan="1" rowspan="1" style="display: table-cell; text-align: left;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>categórico nominal, str</span></p></div></div></td></tr><tr><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>director</span></p></div></div></td><td colspan="1" rowspan="1" style="display: table-cell; text-align: left;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>categórico nominal, str</span></p></div></div></td></tr><tr><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>country</span></p></div></div></td><td colspan="1" rowspan="1" style="display: table-cell; text-align: left;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>categórico nominal, str</span></p></div></div></td></tr><tr><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>date_added</span></p></div></div></td><td colspan="1" rowspan="1" class="selected" style="display: table-cell; text-align: left;"><div class="wrap"><div class="" contenteditable="false" style="margin: 10px 5px;"><p><span>numérico, int</span></p></div></div></td></tr><tr><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>release_year</span></p></div></div></td><td colspan="1" rowspan="1" class="selected" style="display: table-cell; text-align: left; vertical-align: top;"><div class="wrap"><div style="margin: 10px 5px;"><p><span>numérico, int</span></p></div></div></td></tr><tr><td colspan="1" rowspan="1" style="display: table-cell; text-align: left; font-weight: bold;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>category</span></p></div></div></td><td colspan="1" rowspan="1" style="display: table-cell; text-align: left;" class="selected"><div class="wrap"><div style="margin: 10px 5px;"><p><span>categórico nominal, str</span></p></div></div></td></tr></table>

In [11]:
df_netflix_catalogue.isnull()

       type  title  director  country  date_added  release_year  category
0     False  False     False    False       False         False     False
1     False  False      True    False       False         False     False
2     False  False     False     True       False         False     False
3     False  False      True     True       False         False     False
4     False  False      True    False       False         False     False
...     ...    ...       ...      ...         ...           ...       ...
8802  False  False     False    False       False         False     False
8803  False  False      True     True       False         False     False
8804  False  False     False    False       False         False     False
8805  False  False     False    False       False         False     False
8806  False  False     False    False       False         False     False

[8807 rows x 7 columns]

In [12]:
df_netflix_catalogue

,type,title,director,country,date_added,release_year,category
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,Documentaries
1,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,"International TV Shows, TV Dramas, TV Mysteries"
2,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,"Crime TV Shows, International TV Shows, TV Act..."
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,"Docuseries, Reality TV"
4,TV Show,Kota Factory,NaN,India,2021-09-24,2021,"International TV Shows, Romantic TV Shows, TV ..."
...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,United States,2019-11-20,2007,"Cult Movies, Dramas, Thrillers"
8803,TV Show,Zombie Dumb,NaN,NaN,2019-07-01,2018,"Kids' TV, Korean TV Shows, TV Comedies"
8804,Movie,Zombieland,Ruben Fleischer,United States,2019-11-01,2009,"Comedies, Horror Movies"
8805,Movie,Zoom,Peter Hewitt,United States,2020-01-11,2006,"Children & Family Movies, Comedies"
8806,Movie,Zubaan,Mozez Singh,India,2019-03-02,2015,"Dramas, International Movies, Music & Musicals"

In [13]:
df_netflix_catalogue.index

RangeIndex(start=0, stop=8807, step=1)

In [14]:
s_title = pd.Series(['title'])
s_title.is_unique

True

In [15]:
df_netflix_catalogue['type'].value_counts()

Movie      6131
TV Show    2676
Name: type, dtype: int64

In [16]:
df_netflix_catalogue['release_year'].value_counts()

2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1959       1
1925       1
1961       1
1947       1
1966       1
Name: release_year, Length: 74, dtype: int64

In [17]:
df_netflix_catalogue['release_year'].min()

1925

In [18]:
df_netflix_catalogue['release_year'].max()

2021

In [19]:
df_netflix_catalogue['country'].value_counts()

United States                             2818
India                                      972
United Kingdom                             419
Japan                                      245
South Korea                                199
                                          ...
Romania, Bulgaria, Hungary                   1
Uruguay, Guatemala                           1
France, Senegal, Belgium                     1
Mexico, United States, Spain, Colombia       1
United Arab Emirates, Jordan                 1
Name: country, Length: 748, dtype: int64

In [20]:
df_netflix_catalogue['director'].value_counts()

Rajiv Chilaka                     19
Raúl Campos, Jan Suter            18
Marcus Raboy                      16
Suhas Kadav                       16
Jay Karas                         14
                                  ..
Raymie Muzquiz, Stu Livingston     1
Joe Menendez                       1
Eric Bross                         1
Will Eisenberg                     1
Mozez Singh                        1
Name: director, Length: 4528, dtype: int64

In [21]:
df_netflix_catalogue['category'].value_counts()

Dramas, International Movies                          362
Documentaries                                         359
Stand-Up Comedy                                       334
Comedies, Dramas, International Movies                274
Dramas, Independent Movies, International Movies      252
                                                     ...
Kids' TV, TV Action & Adventure, TV Dramas              1
TV Comedies, TV Dramas, TV Horror                       1
Children & Family Movies, Comedies, LGBTQ Movies        1
Kids' TV, Spanish-Language TV Shows, Teen TV Shows      1
Cult Movies, Dramas, Thrillers                          1
Name: category, Length: 514, dtype: int64

In [22]:
df_netflix_final = df_netflix_catalogue
df_netflix_final.category = (df_netflix_final.category.str.split(','))

In [23]:
df_netflix_final

,type,title,director,country,date_added,release_year,category
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,[Documentaries]
1,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,"[International TV Shows, TV Dramas, TV Myste..."
2,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,"[Crime TV Shows, International TV Shows, TV ..."
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,"[Docuseries, Reality TV]"
4,TV Show,Kota Factory,NaN,India,2021-09-24,2021,"[International TV Shows, Romantic TV Shows, ..."
...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,United States,2019-11-20,2007,"[Cult Movies, Dramas, Thrillers]"
8803,TV Show,Zombie Dumb,NaN,NaN,2019-07-01,2018,"[Kids' TV, Korean TV Shows, TV Comedies]"
8804,Movie,Zombieland,Ruben Fleischer,United States,2019-11-01,2009,"[Comedies, Horror Movies]"
8805,Movie,Zoom,Peter Hewitt,United States,2020-01-11,2006,"[Children & Family Movies, Comedies]"
8806,Movie,Zubaan,Mozez Singh,India,2019-03-02,2015,"[Dramas, International Movies, Music & Music..."

In [24]:
df_netflix_final.category.get(1)[0]

#df_netflix_titles.date_added = pd.to_datetime(df_netflix_titles.date_added)

'International TV Shows'

In [25]:
get_first_category = lambda x: x[0]

print(get_first_category(df_netflix_final.category.get(0)))

Documentaries

In [34]:
df_netflix_final.category = get_first_category(df_netflix_final.category.get(0))

In [35]:
df_netflix_final

,type,title,director,country,date_added,release_year,category
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,Documentaries
1,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,Documentaries
2,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,Documentaries
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,Documentaries
4,TV Show,Kota Factory,NaN,India,2021-09-24,2021,Documentaries
...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,United States,2019-11-20,2007,Documentaries
8803,TV Show,Zombie Dumb,NaN,NaN,2019-07-01,2018,Documentaries
8804,Movie,Zombieland,Ruben Fleischer,United States,2019-11-01,2009,Documentaries
8805,Movie,Zoom,Peter Hewitt,United States,2020-01-11,2006,Documentaries
8806,Movie,Zubaan,Mozez Singh,India,2019-03-02,2015,Documentaries

In [38]:
df_netflix_final = df_netflix_catalogue
#df_netflix_final.category = df_netflix_final.category.apply(get_first_category(df_netflix_final.category))
df_netflix_final

,type,title,director,country,date_added,release_year,category
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,Documentaries
1,TV Show,Blood & Water,NaN,South Africa,2021-09-24,2021,Documentaries
2,TV Show,Ganglands,Julien Leclercq,NaN,2021-09-24,2021,Documentaries
3,TV Show,Jailbirds New Orleans,NaN,NaN,2021-09-24,2021,Documentaries
4,TV Show,Kota Factory,NaN,India,2021-09-24,2021,Documentaries
...,...,...,...,...,...,...,...
8802,Movie,Zodiac,David Fincher,United States,2019-11-20,2007,Documentaries
8803,TV Show,Zombie Dumb,NaN,NaN,2019-07-01,2018,Documentaries
8804,Movie,Zombieland,Ruben Fleischer,United States,2019-11-01,2009,Documentaries
8805,Movie,Zoom,Peter Hewitt,United States,2020-01-11,2006,Documentaries
8806,Movie,Zubaan,Mozez Singh,India,2019-03-02,2015,Documentaries